// @ts-nocheck
// eslint-disable 
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/@bracketed/vite-plugin-router
// https://github.com/bracketed/vite-router

import type { Props } from '@bracketed/vite-plugin-router/types';
import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';


const R0 = lazy(() => import('./pages/'));
const R1 = lazy(() => import('./pages/PageNotFound'));
const R2 = lazy(() => import('./pages/signin'));
const R3 = lazy(() => import('./pages/signup'));


/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/@bracketed/vite-plugin-router
 * @link https://github.com/bracketed/vite-router
 */
export function AppRoutes(props: Props) {
  return (
    <BrowserRouter>
	
        <Routes>
          <Route path={"/"} key={"/"} element={<R0 Location={"Home"} Description={"Home page of the website."}></R0>}></Route>
<Route path={"/*"} key={"/*"} element={<R1></R1>}></Route>
<Route path={"/signin"} key={"/signin"} element={<R2 Location={"Sign In"} Description={"Sign in to Impress Web."}></R2>}></Route>
<Route path={"/signup"} key={"/signup"} element={<R3 Location={"Sign Up"} Description={"Sign up to Impress Web."}></R3>}></Route>
		  
		  
        </Routes>
       
    </BrowserRouter>
  );
}